version: '3'
services:
  nginx_force_association:
    build: ./docker/nginx
    ports:
      - '80:80'
      - '443:443'
      # - '4949:4949'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/laravel:/var/www/
    links:
      - mysql
      - php
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  php:
    build: ./docker/php73
    image: app_php:7.3-fpm
    container_name: php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/laravel:/var/www/
    links:
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  mysql:
    build: ./docker/mysql80
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/usr/data
      - ./docker/mysql80/init_sqls:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Tokyo
      MYSQL_USER: user_docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: ForceAssociation_db
      MYSQL_ROOT_PASSWORD: test_docker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=test_docker
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - /sessions
volumes:
  mysql-data: